#cloud-config
# (the above line *must not* have a space between the octothorpe and cloud-config)
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  version: 1
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &primary-arches
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &port-arches
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *primary-arches
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *port-arches
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: false
  identity:
    hostname: e1-attack
    realname: e1-attack
    username: e1-attack
    # TODO(arc) this is not very cybersecure
    password: $6$gROBJOPHfKdQdKtP$AG3AT04HUyDwG5pnUgU5n0swoIZbFGdP5xHCnHy32wuMv.GmtHBXCRyKMlTnHUO8blSQbLd77Fyto9ijQkZq61
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      ens33:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-desktop-minimal
    search_drivers: false
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: true
      id: disk-sda
      type: disk
    - device: disk-sda
      size: 1048576
      flag: bios_grub
      number: 1
      preserve: false
      offset: 1048576
      path: /dev/sda1
      id: partition-0
      type: partition
    - device: disk-sda
      size: 21471690752
      wipe: superblock
      number: 2
      preserve: false
      offset: 2097152
      path: /dev/sda2
      id: partition-1
      type: partition
    - fstype: ext4
      volume: partition-1
      preserve: false
      id: format-0
      type: format
    - path: /
      device: format-0
      id: mount-0
      type: mount
  timezone: America/Los_Angeles
  updates: security
