---
- name: Unsecure sshd
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "yes" }
    - { key: "PasswordAuthentication", value: "yes" }
  notify:
    - restart sshd
