---
- name: Remove Default Ubuntu Repos
  ansible.builtin.deb822_repository:
    name: ubuntu
    enabled: false

- name: Set Ubuntu Updates Repo
  ansible.builtin.deb822_repository:
    name: e1-malware-updates
    types: deb
    uris: http://mirrors.ocf.berkeley.edu/ubuntu-ports/
    suites: [noble, noble-updates, noble-backports]
    components: [main, restricted, universe, multiverse]
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Set Ubuntu Security Repo
  ansible.builtin.deb822_repository:
    name: e1-malware-security
    types: deb
    uris: http://mirrors.ocf.berkeley.edu/ubuntu-ports/
    suites: [noble-security]
    components: [main, restricted, universe, multiverse]
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
