---
- name: Update Attack VM
  hosts: e1-attack,e1-attack.local
  remote_user: root

  tasks:
    - name: Copy/Update Update Script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../vm-update.sh"
        dest: /usr/bin/vm-update
        owner: root
        group: root
        mode: "0755"

    - name: Copy/Update start-record command
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../start-record"
        dest: /usr/bin/start-record
        owner: root
        group: root
        mode: "0755"

    - name: Copy/Update start-record rc file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../.record_rc"
        dest: /home/e1-attack/.record_rc
        owner: e1-attack
        group: e1-attack
        mode: "0644"

    - name: Allow Update Script to be Run Without a Password
      community.general.sudoers:
        name: vm-update-passwordless
        group: e1-attack
        commands: /usr/bin/vm-update
        nopassword: true

    - name: Save 2 Minutes of Boot Time With This One Simple Trick
      ansible.builtin.systemd_service:
        name: systemd-networkd-wait-online.service
        masked: true

    - name: This Course Sponsored by Berkeley
      ansible.builtin.import_tasks: tasks/use-berkeley-mirrors.yaml
      when: ansible_architecture == "aarch64"

    - name: Install Random APT Packages
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - python-is-python3
          - git
          - nano
          - openssh-server
          - open-vm-tools
          - open-vm-tools-desktop
          - neofetch
          - gh
          - sl
          - openvpn
          - curl
          - wget
          - nmap
          - net-tools
          - smbclient
          - nfs-common
    - name: Install random snap Packages
      community.general.snap:
        name:
          - searchsploit

    - name: Pull Scavenger Hunt
      become: true
      become_user: e1-attack
      ansible.builtin.git:
        repo: https://github.com/ucla-e1-malware/linux-scavenger-hunt.git
        dest: /home/e1-attack/linux-scavenger-hunt
        version: main
        force: true

    - name: Download Wordlists
      ansible.builtin.git:
        repo: https://github.com/ucla-e1-malware/KaliLists.git
        dest: /usr/share/wordlists
        version: main
        force: true

    - name: Unzip rockyou.txt
      ansible.builtin.unarchive:
        remote_src: true
        src: /usr/share/wordlists/rockyou.txt.gz
        dest: /usr/share/wordlists/

    - name: Update to .local hostname format
      ansible.builtin.hostname:
        name: e1-attack.local
