---
- name: Update Attack VMs
  hosts: localhost
  remote_user: root

  tasks:
    - name: This Course Sponsored by Berkeley
      ansible.builtin.import_tasks: tasks/use-berkeley-mirrors.yaml
      when: ansible_architecture == "aarch64"

    - name: Install Random APT Packages
      ansible.builtin.apt:
        pkg:
          - python-is-python3
          - git
          - nano
          - open-vm-tools
          - open-vm-tools-desktop

    - name: Pull Scavenger Hunt
      become: true
      become_user: e1-attack
      ansible.builtin.git:
        repo: https://github.com/ucla-e1-malware/linux-scavenger-hunt.git
        dest: /home/e1-attack/linux-scavenger-hunt
        version: main
        force: true
